#!/usr/bin/env python3
"""Token Renderer — 将设计令牌渲染为 CSS / HTML 片段"""

import json


def render_css_variables(token_dict):
    """从令牌 JSON 生成 :root CSS 变量"""
    css = "/* Auto-generated by Site Settings — Design Tokens */\n"
    css += ":root {\n"

    # 颜色
    for k, v in token_dict.get('colors', {}).items():
        css += f"  --color-{k}: {v};\n"
    css += "  --color-brand-primary: var(--color-primary);\n"
    css += "  --color-brand-accent: var(--color-accent);\n"

    # 排版
    for k, v in token_dict.get('typography', {}).items():
        css += f"  --font-{k}: {v};\n"

    # 间距
    for k, v in token_dict.get('spacing', {}).items():
        css += f"  --space-{k}: {v};\n"

    # 圆角
    for k, v in token_dict.get('border_radius', {}).items():
        css += f"  --radius-{k}: {v};\n"

    # 阴影
    for k, v in token_dict.get('shadows', {}).items():
        css += f"  --shadow-{k}: {v};\n"

    css += "}\n"
    return css


def render_navigation_html(token_dict):
    """从令牌生成导航 HTML"""
    items = token_dict.get('navigation', {}).get('items', [])
    if not items:
        return '<!-- No navigation items -->'

    html = '<nav class="site-nav">\n  <ul class="nav-list">\n'
    for item in items:
        title = item.get('title', '')
        url = item.get('url', '#')
        target = item.get('target', '_self')
        children = item.get('children', [])

        if children:
            html += f'    <li class="nav-item has-dropdown">\n'
            html += f'      <a href="{url}" target="{target}">{title}</a>\n'
            html += '      <ul class="nav-dropdown">\n'
            for child in children:
                html += f'        <li><a href="{child.get("url", "#")}">{child.get("title", "")}</a></li>\n'
            html += '      </ul>\n'
            html += '    </li>\n'
        else:
            html += f'    <li class="nav-item"><a href="{url}" target="{target}">{title}</a></li>\n'
    html += '  </ul>\n</nav>'
    return html


def render_footer_html(token_dict):
    """从令牌生成页脚 HTML"""
    footer = token_dict.get('footer', {})
    sections = footer.get('sections', [])
    articles = footer.get('articles', [])
    copyright_text = footer.get('copyright', '')
    icp = footer.get('icp_number', '')
    security = footer.get('security_number', '')
    brand = token_dict.get('brand', {})

    html = '<footer class="site-footer">\n  <div class="footer-grid">\n'

    # 品牌信息
    html += '    <div class="footer-brand">\n'
    if brand.get('logo_url'):
        html += f'      <img src="{brand["logo_url"]}" alt="{brand.get("site_name", "")}" class="footer-logo">\n'
    html += f'      <p class="footer-desc">{brand.get("slogan", "")}</p>\n'
    html += '    </div>\n'

    # 链接分组
    for section in sections:
        name = section.get('name', '')
        links = section.get('links', [])
        html += f'    <div class="footer-section">\n'
        html += f'      <h4>{name}</h4>\n      <ul>\n'
        for link in links:
            html += f'        <li><a href="{link.get("url", "#")}">{link.get("title", "")}</a></li>\n'
        html += '      </ul>\n    </div>\n'

    html += '  </div>\n'

    # 底部栏
    html += '  <div class="footer-bottom">\n'
    if articles:
        html += '    <div class="footer-legal">\n'
        for a in articles:
            html += f'      <a href="{a.get("url", "#")}">{a.get("title", "")}</a>\n'
        html += '    </div>\n'

    html += f'    <p class="footer-copyright">{copyright_text}</p>\n'
    if icp:
        html += f'    <p class="footer-icp">{icp}</p>\n'
    if security:
        html += f'    <p class="footer-security">{security}</p>\n'
    html += '  </div>\n</footer>'
    return html


def render_brand_meta(token_dict):
    """生成品牌相关的 meta 标签"""
    brand = token_dict.get('brand', {})
    seo = token_dict.get('seo', {})

    meta = ''
    meta += f'<title>{seo.get("title") or brand.get("site_name", "")}</title>\n'
    if seo.get('description'):
        meta += f'<meta name="description" content="{seo["description"]}">\n'
    if brand.get('favicon_url'):
        meta += f'<link rel="icon" href="{brand["favicon_url"]}">\n'
    return meta


def render_all(token_dict):
    """一次性渲染所有输出"""
    return {
        'css': render_css_variables(token_dict),
        'nav_html': render_navigation_html(token_dict),
        'footer_html': render_footer_html(token_dict),
        'brand_meta': render_brand_meta(token_dict),
    }