#!/usr/bin/env python3
"""CMS Page Generator — Write LLM page content into cms_blocks / cms_posts tables

v2.1.0 起 cms_blocks / cms_posts 位于主库，本生成器经 main_site 内部
API（internal_client）读写区块数据（默认草稿 is_published=0）。
"""

import json


class PageGenerator:
    """CMS page block generator"""

    @staticmethod
    def apply_page_blocks(page: str, sections_data: list, draft=False):
        """Write page block data into cms_blocks table (idempotent: clear then write)

        page: page identifier, e.g. 'home', 'about', 'services'
        sections_data: list of sections returned by LLM
        draft: if True, writes with is_published=0
        """
        blocks = []
        position = 0
        for section in sections_data:
            position += 1
            block_type = section.get('block_type', 'text')
            title = section.get('title', '')
            subtitle = section.get('subtitle', '')
            section_name = section.get('section_name', block_type)

            # Handle items list (features, services blocks)
            items = section.get('items', [])
            if items:
                # Each item as an independent block
                for item in items:
                    position += 1
                    blocks.append({
                        'page': page,
                        'section': section_name,
                        'block_type': 'feature' if block_type == 'features' else 'text',
                        'position': position,
                        'title': item.get('title', ''),
                        'subtitle': item.get('description', ''),
                        'content': item.get('description', ''),
                        'link_text': 'Learn More',
                        'link_url': f"/{page}",
                        'icon': item.get('icon', ''),
                        'extra_json': {},
                    })
            else:
                # Single block (hero, cta, text)
                blocks.append({
                    'page': page,
                    'section': section_name,
                    'block_type': block_type,
                    'position': position,
                    'title': title,
                    'subtitle': subtitle,
                    'content': section.get('description', subtitle),
                    'link_text': section.get('cta_text', ''),
                    'link_url': section.get('cta_url', '/'),
                    'icon': '',
                    'extra_json': {},
                })

        is_pub = 0 if draft else 1
        from ..internal_client import replace_draft_blocks, clear_cache
        replace_draft_blocks(page=page, blocks=blocks, is_published=is_pub)
        clear_cache()
        mode = 'draft' if draft else 'production'
        print(f'[SiteBuilder] ✅ Page "{page}" applied ({mode}): {len(sections_data)} sections')

    @staticmethod
    def apply_page_text(page: str, text_data: dict, draft=False):
        """Write simple text page (e.g. about us, service areas — non-block pages)

        text_data: JSON returned by LLM (contains 'content' or 'sections' field)
        draft: if True, writes with is_published=0
        """
        # Try to extract sections first
        sections = text_data.get('sections', [])
        if sections:
            PageGenerator.apply_page_blocks(page, sections, draft=draft)
            return

        # Plain text page: write a single text block
        is_pub = 0 if draft else 1
        content = text_data.get('content', '') or json.dumps(text_data, ensure_ascii=False)
        from ..internal_client import replace_draft_blocks, clear_cache
        replace_draft_blocks(page=page, blocks=[{
            'page': page,
            'section': 'main',
            'block_type': 'text',
            'position': 1,
            'title': page,
            'subtitle': '',
            'content': content,
            'icon': '',
            'image_url': '',
            'link_text': '',
            'link_url': '',
            'extra_json': {},
        }], is_published=is_pub)
        clear_cache()
        mode = 'draft' if draft else 'production'
        print(f'[SiteBuilder] ✅ Page "{page}" applied ({mode}, text mode)')

    @staticmethod
    def apply_document(slug: str, title: str, html_content: str, draft=False):
        """Write legal document into cms_posts table

        slug: document identifier (e.g. privacy_policy, terms_of_service)
        title: document title
        html_content: HTML content generated by LLM
        draft: if True, writes with is_published=0
        """
        is_pub = 0 if draft else 1
        from ..internal_client import write_document, clear_cache
        write_document(slug, title, html_content, is_published=is_pub)
        clear_cache()
        mode = 'draft' if draft else 'production'
        print(f'[SiteBuilder] ✅ Document "{slug}" applied ({mode})')

    @staticmethod
    def modify_block(block_id: int, changes: dict):
        """Minimal edit: update specific fields of a single block

        changes: {"title": "New Title", "content": "New Content", ...}
        """
        allowed_fields = ['title', 'subtitle', 'content', 'link_text', 'link_url', 'image_url', 'icon']
        updated = []
        for key, val in changes.items():
            if key in allowed_fields:
                try:
                    from ..internal_client import update_block
                    update_block(block_id, key, val)
                    updated.append(key)
                except Exception:
                    continue
        if not updated:
            return False
        from ..internal_client import clear_cache
        clear_cache()
        print(f'[SiteBuilder] ✅ Block #{block_id} modified: {updated}')
        return True

    @staticmethod
    def get_page_summary(page: str) -> list:
        """Get summary of all blocks for a page (used by LLM modification context)"""
        from ..internal_client import get_page_blocks
        rows = get_page_blocks(page)
        return [{
            'id': r['id'],
            'block_type': r['block_type'],
            'section': r['section'],
            'title': (r['title'] or '')[:80],
            'content_preview': (r['content'] or '')[:100],
        } for r in rows]
